# -*- coding: utf-8 -*-
"""Assignment no 11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fp0lCLpzD3AsXFpzmUbyy1Sgy3PD0aar
"""

# Initialize variables
pollution_level = 0  # Initial pollution level
pollution_increase_rate = 10  # Rate of pollution increase per minute
purifier_rate = 2  # Rate of purification per minute
simulation_duration = 30  # Duration of the simulation in minutes

# Lists to store pollution levels and time steps
pollution_levels = []
time_steps = []

# Simulation loop
for t in range(simulation_duration + 1):
    pollution_levels.append(pollution_level)
    time_steps.append(t)

    # Increase pollution
    pollution_level += pollution_increase_rate

    # Reduce pollution by the air purifier
    pollution_level -= purifier_rate

    # Ensure pollution level doesn't go negative
    pollution_level = max(0, pollution_level)

# Display results
print("Time (minutes) | Pollution Level")
print("-" * 31)

for t, pollution in zip(time_steps, pollution_levels):
    print(f"{t:^15} | {pollution:^13}")

# Final pollution level
final_pollution = pollution_levels[-1]
print("\nFinal Pollution Level:", final_pollution)

if final_pollution <= 5:
    print("The air purifier successfully reduced pollution to a safe level.")
else:
    print("The air purifier was not able to reduce pollution to a safe level.")